name: getjob-ai

include:
  - gateway/compose.yml
  - db/compose.yml
  - migrations/compose.yml
  - core-api/compose.yml
  - rabbitmq/compose.yml
  - event-relay/compose.yml

networks:
  proxy_network:
