services:
  gateway:
    container_name: gateway
    restart: unless-stopped

    build:
      context: ./gateway/
      dockerfile: Dockerfile

    environment:
      - DOMAIN=${DOMAIN}
      - CLERK_ENDPOINT=${CLERK_ENDPOINT}
      - ADMIN_EMAIL=${ADMIN_EMAIL}

    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"

    volumes:
      - ./gateway/Caddyfile:/etc/caddy/Caddyfile
      - resumes:/shared-data/resumes
      - gateway_data:/data
      - gateway_config:/config

    networks:
      - proxy_network

volumes:
  gateway_data:
  gateway_config:
  resumes:
