@startuml

skinparam defaultTextAlignment center

<style>
.db {
    MinimumWidth 400
}
.event_bus {
    MinimumWidth 400
}
</style>

package "Client apps" <<system_boundary>> {
    rectangle "Frontend Web App" as frontend <<microservice>>
}

package "Docker Host" <<system_boundary>> {
    node "API Gateway" as gateway <<microservice>>

    node "Core API" as core_api <<microservice>>
    node "Event-Relay" as event_relay <<microservice>>
    node "Vectoriser" as vectoriser <<microservice>>
    node "Parser" as parser <<microservice>>
    node "Optimiser" as optimiser <<microservice>>
    node "ATS Scorer" as ats_scorer <<microservice>>
    node "PDF Generator" as pdf_generator <<microservice>>

    database "PostgreSQL 18" as db <<db>>
    database "Qdrant" as qdrant <<vector db>>

    queue "RabbitMQ" as rmq <<event_bus>>
}


frontend .r.> gateway : HTTPS

gateway -r-> core_api : HTTP
gateway --> pdf_generator : HTTP
core_api .r.> event_relay : PG LISTEN/NOTIFY

core_api ---> db : TCP/IP
event_relay ---> db : TCP/IP
vectoriser ---> db : TCP/IP
ats_scorer ---> db : TCP/IP
parser ---> db : TCP/IP
optimiser ---> db : TCP/IP

vectoriser --> qdrant : gRPC
ats_scorer --> qdrant : gRPC

event_relay -up-> rmq : AMQP
vectoriser -up-> rmq : AMQP
ats_scorer -up-> rmq : AMQP
parser -up-> rmq : AMQP
optimiser -up-> rmq : AMQP

@enduml
