@startuml

left to right direction
skinparam defaultTextAlignment center

actor "User" as User
actor "Clerk\nIdentity Provider" as Clerk
actor "LLM Provider" as LLM

rectangle "Authentication & Account" {
    usecase "Реєстрація" as UC_Register
    usecase "Вхід" as UC_Login
    usecase "Верифікація приналежності\nдо акаунту" as UC_VerifyEmail
    usecase "Відновлення пароля" as UC_RecoverPassword
    usecase "Зміна пароля" as UC_ChangePassword
    usecase "Управління профілем" as UC_Profile
    usecase "Експорт даних користувача" as UC_ExportData
    usecase "Видалення акаунту" as UC_Delete
}

rectangle "Resume Input" {
    usecase "Завантаження документу" as UC_Upload
    usecase "NLP Парсинг" as UC_Parse
    usecase "Рев'ю результатів парсингу" as UC_ReviewParse

    usecase "Завантаження LinkedIn ZIP" as UC_Zip
    usecase "Парсинг CSV" as UC_ParseZip

    usecase "Ручне введення" as UC_Wizard
}

rectangle "Optimization" {
    usecase "XYZ Coach" as UC_XYZ
    usecase "Генерація супровідного листа" as UC_Cover
    usecase "ATS оптимізація" as UC_ATSOpt
}

rectangle "ATS Scoring" as PkgATS {
    usecase "Розрахунок ATS Score" as UC_ATS_Calc
    usecase "Перегляд відсутніх ключових слів" as UC_ATS_Breakdown
}

rectangle "Export" {
    usecase "Перегляд ATS Score" as UC_ExportATS
    usecase "Експорт резюме" as UC_ExportRes
}

User -- UC_Register
User -- UC_Login
User -- UC_RecoverPassword
User -- UC_ChangePassword
User -- UC_Profile
User -- UC_ExportData
User -- UC_Delete

UC_Register -- Clerk
UC_Login -- Clerk
UC_VerifyEmail -- Clerk
UC_RecoverPassword ..> UC_VerifyEmail : <<include>>
UC_ChangePassword ..> UC_VerifyEmail : <<include>>

User -- UC_Wizard

User -- UC_Upload
UC_Upload ..> UC_Parse : <<include>>
UC_ReviewParse <.. UC_Upload : <<extend>>
User -- UC_ReviewParse

User -- UC_Zip
UC_Zip ..> UC_ParseZip : <<include>>

UC_XYZ -- LLM
UC_ATSOpt -- LLM
UC_Cover -- LLM

User -- UC_ExportRes
User -- UC_ExportATS

UC_ExportRes <.. UC_ATSOpt : <<extend>>

UC_ATSOpt .l.> UC_ATS_Calc : <<include>>
UC_ATS_Breakdown <.. UC_ATS_Calc : <<extend>>
User -- UC_ATS_Breakdown

UC_ExportATS ..> UC_ATS_Calc : <<include>>
UC_ATSOpt <.. UC_Cover : <<extend>>
UC_ATSOpt <.. UC_XYZ : <<extend>>
@enduml
